apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL:
    targetRevision: HEAD
    path: platform-gitops/apps/backend/base
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true    